[package]
name = "os_project"
version = "0.1.0"
authors = ["Steve <sshoemaker@smu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "*"
priority-queue = "*"
text_io = "0.1.8"